DELIMITER $$
SET GLOBAL event_scheduler=ON$$
CREATE DEFINER=`root`@`localhost` EVENT `SetMonthlyTokens` ON SCHEDULE EVERY 1 MONTH STARTS '2023-10-01 00:00:01' ON COMPLETION NOT PRESERVE ENABLE DO CALL SetMonthlyTokens()$$
CREATE DEFINER=`root`@`localhost` EVENT `DistributeTokens` ON SCHEDULE EVERY 1 MONTH STARTS LAST_DAY(CURDATE()) ON COMPLETION NOT PRESERVE ENABLE DO CALL DistributeTokens()$$
DELIMITER ;
